[profile.default]
src = "src"
out = "out"
test = "test"
script = "script"
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
  "forge-std/=lib/forge-std/src/",
  "poseidon-solidity/=node_modules/poseidon-solidity/",
  "@openzeppelin/=node_modules/@openzeppelin/",
  "v4-core/=lib/v4-core/",
  "v4-periphery/=lib/v4-periphery/",
  "@uniswap/v4-core/=lib/v4-core/",
  "permit2/=lib/v4-periphery/lib/permit2/",
]

[rpc_endpoints]
ethereum_sepolia = "${SEPOLIA_RPC_URL}"
